### PR TITLE
Fix hls stream manifest

### PR DESCRIPTION
**Pull request by relictMarauder**
Rebase implementation of  #288 and add fix for audio-stream's language-property

### CODE REVIEW

**Comment by quarckster** [comment]
By the way, I couldn't reproduce the issue for `/item/view/84499/Enola-Holmes-2`.

```
curl -H "Authorization: Bearer <my token>" "https://<REDACTED>.m3u8"

...
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=9278652,VIDEO-RANGE=SDR,RESOLUTION=3840x1600,CODECS="avc1.640028,mp4a.40.2",FRAME-RATE=24,HDCP-LEVEL=NONE,AUDIO="audio2160",SUBTITLES="sub"
https://<REDACTED>
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1159831,VIDEO-RANGE=SDR,RESOLUTION=3840x1600,CODECS="avc1.640028,mp4a.40.2",HDCP-LEVEL=NONE,URI="https://<REDACTED>"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3267543,VIDEO-RANGE=SDR,RESOLUTION=1920x800,CODECS="avc1.640028,mp4a.40.2",FRAME-RATE=24,HDCP-LEVEL=NONE,AUDIO="audio1080",SUBTITLES="sub"
https://<REDACTED>
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=408442,VIDEO-RANGE=SDR,RESOLUTION=1920x800,CODECS="avc1.640028,mp4a.40.2",HDCP-LEVEL=NONE,URI="<REDACTED>"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1664258,VIDEO-RANGE=SDR,RESOLUTION=1280x534,CODECS="avc1.640028,mp4a.40.2",FRAME-RATE=24,HDCP-LEVEL=NONE,AUDIO="audio720",SUBTITLES="sub"
https://<REDACTED>
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=208032,VIDEO-RANGE=SDR,RESOLUTION=1280x534,CODECS="avc1.640028,mp4a.40.2",HDCP-LEVEL=NONE,URI="https://<REDACTED>"

I don't see duplicated streams. I enabled HEVC and 4K on kinopub.
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=834703,VIDEO-RANGE=SDR,RESOLUTION=720x300,CODECS="avc1.640028,mp4a.40.2",FRAME-RATE=24,HDCP-LEVEL=NONE,AUDIO="audio480",SUBTITLES="sub"
https://<REDACTED>
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104337,VIDEO-RANGE=SDR,RESOLUTION=720x300,CODECS="avc1.640028,mp4a.40.2",HDCP-LEVEL=NONE,URI="https://<REDACTED>"
```

**Comment by relictMarauder** [comment]
> 

The manifest for this and another streams with such problem corrupt in this way:
if you configured **HLS4 and 4k**:
   you don't have any double streams and all video streams are defined **correctly**  (codec  defined  as avc1 and stream is encoded with this codec), you will receive only 4 video-streams.
if you configured **HLS4 and 4k and HEVC**:
     you don't have any double streams and all video streams are defined **not correctly**  (codec  defined  as avc1 and stream is encoded whit codec hvc1), you will receive only 4 video-streams.
if you configured **HLS4, 4k, HEVC and mixed playlist**:
     you have double streams and one half of video streams are defined  **correctly** and another half  **not correctly**  (codec  defined as avc1 and stream is encoded whit codec hvc1), you will receive 8 video-streams(4 correct defined as AVC1, and 4 wrong defined as AVC1).

**Comment by quarckster** [comment]
> > 
> 
> The manifest for this and another streams with such problem corrupt in this way: if you configured **HLS4 and 4k**: you don't have any double streams and all video streams are defined **correctly** (codec defined as avc1 and stream is encoded with this codec), you will receive only 4 video-streams. All streams are playable without problems if you configured **HLS4 and 4k and HEVC**: you don't have any double streams and all video streams are defined **not correctly** (codec defined as avc1 and stream is encoded whit codec hvc1), you will receive only 4 video-streams. Non of stream are playable. if you configured **HLS4, 4k, HEVC and mixed playlist**: you have double streams and one half of video streams are defined **correctly** and another half **not correctly** (codec defined as avc1 and stream is encoded whit codec hvc1), you will receive 8 video-streams(4 correctly defined as AVC1, and 4 with wrong definition AVC1). The half of streams are playable

I've asked the android app developer about this issue. Looks like it's not actual and the android app doesn't have any workaround.

**Comment by quarckster** [comment]
Closed as non-actual. Feel free to reopen if you think it's still needs to be fixed.

**Pull request closed without merging**
